// Get sll without search params
export const GET_TITLES_REQUEST = 'GET_TITLES_REQUEST';
export const GET_TITLES_SUCCESS = 'GET_TITLES_SUCCESS';
export const GET_TITLES_ERROR = 'GET_TITLES_ERROR';

// Get single title
export const GET_TITLE_REQUEST = 'GET_TITLE_REQUEST';
export const GET_TITLE_SUCCESS = 'GET_TITLE_SUCCESS';
export const GET_TITLE_ERROR = 'GET_TITLE_ERROR';

// Edit single title
export const PUT_TITLE_REQUEST = 'PUT_TITLE_REQUEST';
export const PUT_TITLE_SUCCESS = 'PUT_TITLE_SUCCESS';
export const PUT_TITLE_ERROR = 'PUT_TITLE_ERROR';

// Delete single title
export const DELETE_TITLE_REQUEST = 'DELETE_TITLE_REQUEST';
export const DELETE_TITLE_SUCCESS = 'DELETE_TITLE_SUCCESS';
export const DELETE_TITLE_ERROR = 'DELETE_TITLE_ERROR';

// Create new title
export const POST_TITLE_REQUEST = 'POST_TITLE_REQUEST';
export const POST_TITLE_SUCCESS = 'POST_TITLE_SUCCESS';
export const POST_TITLE_ERROR = 'POST_TITLE_ERROR';

// Get more titles
export const GET_MORE_TITLE_REQUEST = 'GET_MORE_TITLE_REQUEST';
export const GET_MORE_TITLE_SUCCESS = 'GET_MORE_TITLE_SUCCESS';
export const GET_MORE_TITLE_ERROR = 'GET_MORE_TITLE_ERROR';

// Search for a title(s)
export const SEARCH_TITLES_REQUEST = 'SEARCH_TITLES_REQUEST';
export const SEARCH_TITLES_SUCCESS = 'SEARCH_TITLES_SUCCESS';
export const SEARCH_TITLES_ERROR = 'SEARCH_TITLES_ERROR';